services:
  postgres:
    image: postgres:15.1-alpine
    container_name: api-postgres-container
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
    networks:
      - fullstack-net
    

  api-golang:
    build:
      context: api-golang
      dockerfile: Dockerfile
    container_name: api-golang-container
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgres://postgres:mysecretpassword@postgres:5432/postgres
    networks:
      - fullstack-net
    depends_on:
      - postgres
    init: true

  api-node:
    build:
      context: api-node
      dockerfile: Dockerfile
    container_name: api-node-container
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgres://postgres:mysecretpassword@postgres:5432/postgres
    networks:
      - fullstack-net
    depends_on:
      - postgres
    init: true

  client-react:
    build:
      context: client-react
      dockerfile: Dockerfile
    container_name: client-react-container
    ports:
      - "3001:3001"
    networks:
      - fullstack-net
    init: true

networks:
  fullstack-net:
    driver: bridge
