services:
  client-react-vite:
    image: client-react-vite
    build:
      context: client-react
      dockerfile: Dockerfile.update
      target: dev
    init: true
    volumes:
      - type: bind
        source: client-react
        target: /usr/src/app/
      - type: volume
        target: /usr/src/app/node_modules 
      - type: bind
        source: client-react/vite.config.js
        target: /usr/src/app/vite.config.js
    networks:
      - frontend
    ports:
      - 3001:3001
  # client-react-nginx:
  #   image: client-react-nginx
  #   build:
  #     context: client-react
  #     dockerfile: Dockerfile.update
  #   init: true
  #   networks:
  #     - frontend
  #   ports:
  #     - 80:8080
  #   restart: unless-stopped
  api-node:
    image: api-node
    build:
      context: api-node
      dockerfile: Dockerfile.update
      target: dev
    init: true
    volumes:
      - type: bind
        source: api-node
        target: /usr/src/app/
      - type: volume
        target: /usr/src/app/node_modules 
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgres://postgres:mysecretpassword@postgres:5432/postgres
    networks:
      - frontend
      - backend  
    ports:
      - 3000:3000
    restart: unless-stopped
  api-golang:
    image: api-golang
    build:
      context: api-golang
      dockerfile: Dockerfile.update
      target: dev
    init: true
    volumes:
      - type: bind
        source: api-golang
        target: /app/
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgres://postgres:mysecretpassword@postgres:5432/postgres
    networks:
      - frontend
      - backend
    ports:
      - 8080:8080
    restart: unless-stopped
  postgres:
    image: postgres:15.1-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
    networks:
      - backend
    ports:
      - 5432:5432
volumes:
  pgdata:
networks:
  frontend:
  backend: