name: Deploy

on:
  push:
    branches:
      - railway  # Runs only on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: 20

    - name: Lint Node.js (ESLint)
      working-directory: ./api-node
      run: |
        npm install
        npx eslint .
    
    - name: Lint React (ESLint)
      working-directory: ./client-react-vite
      run: |
        npm install
        npx eslint .
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.19


    - name: Lint Golang (Staticcheck)
      working-directory: ./api-golang
      run: |
        go install honnef.co/go/tools/cmd/staticcheck@latest
        staticcheck ./...

    